### ISSUE TITLE
Cannot intercept packets and report errors

### ISSUE THREAD

**Issue by lyy905980571** [DigitalSecurity/btlejuice#65]
When I double-click to select a Bluetooth device, btlejuice will report the following error:
[info] Discovering services and characteristics ...
buffer.js:434
      length += list[i].length;
                        ^

TypeError: Cannot read property 'length' of undefined
    at Function.Buffer.concat (buffer.js:434:25)
    at Object.c1 (/root/.nvm/versions/node/v8.9.0/lib/node_modules/btlejuice/node_modules/noble/lib/hci-socket/crypto.js:8:19)
    at Smp.handlePairingResponse (/root/.nvm/versions/node/v8.9.0/lib/node_modules/btlejuice/node_modules/noble/lib/hci-socket/smp.js:86:12)
    at Smp.onAclStreamData (/root/.nvm/versions/node/v8.9.0/lib/node_modules/btlejuice/node_modules/noble/lib/hci-socket/smp.js:57:10)
    at emitTwo (events.js:131:20)
    at AclStream.emit (events.js:214:7)
    at AclStream.push (/root/.nvm/versions/node/v8.9.0/lib/node_modules/btlejuice/node_modules/noble/lib/hci-socket/acl-stream.js:35:10)
    at NobleBindings.onAclDataPkt (/root/.nvm/versions/node/v8.9.0/lib/node_modules/btlejuice/node_modules/noble/lib/hci-socket/bindings.js:286:15)
    at emitThree (events.js:136:13)
    at Hci.emit (events.js:217:7)
node.js version is 8.9.0
I was running btlejuice on two VMs and the bluetooth dongle was bt5.0.

**Comment by pi3ch** [comment]
This seems to be related to underlying library, see https://github.com/abandonware/bleno/issues/23
